### PR TITLE
Mastery Exercise Submission #1

### PR DESCRIPTION
**Pull request by iamericanartist**

### CODE REVIEW

**Comment by iamericanartist** [comment]
@C-Stein
Just an initial tag - nothing to report yet

**Comment by iamericanartist** [comment]
@C-Stein I think I'm like really close! I need to get the error message for no args working

**Comment by C-Stein** [comment]
Nice work @iamericanartist . The comments are really REALLY awesome, but I personally would prefer to see them on separate lines so I don't have to scroll side-to-side to read them. In addition to adding the usage statement, check to make sure capitalized words are being returned where appropriate.

**Comment by iamericanartist** [comment]
@C-Stein - I believe I'm ready for another review. I changed up the comments ("above line" comments seem pretty common, and I see the pros now), added the usage alert, and fixed the "toLowercase()" that I was doing to the output... Let me know if you notice anything else! Thanks!

**Comment by C-Stein** [comment]
👍  Nice work!

**Comment by iamericanartist** [comment]
YUSSS

**Pull request merged**
